//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiSa.Web08.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiSa.Web08.Core.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sach nhan vien.
        /// </summary>
        public static string EmployeeList {
            get {
                return ResourceManager.GetString("EmployeeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string Enum_Gender_Female {
            get {
                return ResourceManager.GetString("Enum_Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string Enum_Gender_Male {
            get {
                return ResourceManager.GetString("Enum_Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        public static string Enum_Gender_Other {
            get {
                return ResourceManager.GetString("Enum_Gender_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành phẩm.
        /// </summary>
        public static string Enum_Type_FinishedProduct {
            get {
                return ResourceManager.GetString("Enum_Type_FinishedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng hóa.
        /// </summary>
        public static string Enum_Type_Goods {
            get {
                return ResourceManager.GetString("Enum_Type_Goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa xác định.
        /// </summary>
        public static string Enum_Type_NotDetermined {
            get {
                return ResourceManager.GetString("Enum_Type_NotDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không giảm thuế.
        /// </summary>
        public static string Enum_Type_NotReduction {
            get {
                return ResourceManager.GetString("Enum_Type_NotReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngừng sử dụng.
        /// </summary>
        public static string Enum_Type_NotUsing {
            get {
                return ResourceManager.GetString("Enum_Type_NotUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguyên vật liệu.
        /// </summary>
        public static string Enum_Type_RawMaterial {
            get {
                return ResourceManager.GetString("Enum_Type_RawMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có giảm thuế.
        /// </summary>
        public static string Enum_Type_Reduction {
            get {
                return ResourceManager.GetString("Enum_Type_Reduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ.
        /// </summary>
        public static string Enum_Type_Service {
            get {
                return ResourceManager.GetString("Enum_Type_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công cụ dụng cụ.
        /// </summary>
        public static string Enum_Type_Tool {
            get {
                return ResourceManager.GetString("Enum_Type_Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang sử dụng.
        /// </summary>
        public static string Enum_Type_Using {
            get {
                return ResourceManager.GetString("Enum_Type_Using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string Excel_col_1 {
            get {
                return ResourceManager.GetString("Excel_col_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên.
        /// </summary>
        public static string Excel_col_2 {
            get {
                return ResourceManager.GetString("Excel_col_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên.
        /// </summary>
        public static string Excel_col_3 {
            get {
                return ResourceManager.GetString("Excel_col_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        public static string Excel_col_4 {
            get {
                return ResourceManager.GetString("Excel_col_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string Excel_col_5 {
            get {
                return ResourceManager.GetString("Excel_col_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí.
        /// </summary>
        public static string Excel_col_6 {
            get {
                return ResourceManager.GetString("Excel_col_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phòng ban.
        /// </summary>
        public static string Excel_col_7 {
            get {
                return ResourceManager.GetString("Excel_col_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số TK.
        /// </summary>
        public static string Excel_col_8 {
            get {
                return ResourceManager.GetString("Excel_col_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ngân hàng.
        /// </summary>
        public static string Excel_col_9 {
            get {
                return ResourceManager.GetString("Excel_col_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhóm vật tư hàng hóa , dịch vụ.
        /// </summary>
        public static string Excel_groupCategory_col_2 {
            get {
                return ResourceManager.GetString("Excel_groupCategory_col_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm vật tư hàng hóa , dịch vụ.
        /// </summary>
        public static string Excel_groupCategory_col_3 {
            get {
                return ResourceManager.GetString("Excel_groupCategory_col_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Excel_groupCategory_col_Status {
            get {
                return ResourceManager.GetString("Excel_groupCategory_col_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng tồn.
        /// </summary>
        public static string Excel_product_col_10 {
            get {
                return ResourceManager.GetString("Excel_product_col_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị tồn.
        /// </summary>
        public static string Excel_product_col_11 {
            get {
                return ResourceManager.GetString("Excel_product_col_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diễn giải khi mua.
        /// </summary>
        public static string Excel_product_col_12 {
            get {
                return ResourceManager.GetString("Excel_product_col_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diễn giải khi bán.
        /// </summary>
        public static string Excel_product_col_13 {
            get {
                return ResourceManager.GetString("Excel_product_col_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản giảm giá.
        /// </summary>
        public static string Excel_product_col_14 {
            get {
                return ResourceManager.GetString("Excel_product_col_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản kho.
        /// </summary>
        public static string Excel_product_col_15 {
            get {
                return ResourceManager.GetString("Excel_product_col_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản trả lại.
        /// </summary>
        public static string Excel_product_col_16 {
            get {
                return ResourceManager.GetString("Excel_product_col_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản doanh thu.
        /// </summary>
        public static string Excel_product_col_17 {
            get {
                return ResourceManager.GetString("Excel_product_col_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản chi phí.
        /// </summary>
        public static string Excel_product_col_18 {
            get {
                return ResourceManager.GetString("Excel_product_col_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản chiết khấu.
        /// </summary>
        public static string Excel_product_col_19 {
            get {
                return ResourceManager.GetString("Excel_product_col_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vật tư , hàng hóa.
        /// </summary>
        public static string Excel_product_col_2 {
            get {
                return ResourceManager.GetString("Excel_product_col_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉ lệ chiết khấu khi mua.
        /// </summary>
        public static string Excel_product_col_20 {
            get {
                return ResourceManager.GetString("Excel_product_col_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn giá mua cố định.
        /// </summary>
        public static string Excel_product_col_21 {
            get {
                return ResourceManager.GetString("Excel_product_col_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn giá mua gần nhất.
        /// </summary>
        public static string Excel_product_col_22 {
            get {
                return ResourceManager.GetString("Excel_product_col_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn giá bán.
        /// </summary>
        public static string Excel_product_col_23 {
            get {
                return ResourceManager.GetString("Excel_product_col_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuế vat.
        /// </summary>
        public static string Excel_product_col_24 {
            get {
                return ResourceManager.GetString("Excel_product_col_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuế nhập khẩu.
        /// </summary>
        public static string Excel_product_col_25 {
            get {
                return ResourceManager.GetString("Excel_product_col_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuế xuất khẩu.
        /// </summary>
        public static string Excel_product_col_26 {
            get {
                return ResourceManager.GetString("Excel_product_col_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm hàng hóa chiu thuế đặc biệt.
        /// </summary>
        public static string Excel_product_col_27 {
            get {
                return ResourceManager.GetString("Excel_product_col_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Excel_product_col_28 {
            get {
                return ResourceManager.GetString("Excel_product_col_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại vật tư , hàng hóa.
        /// </summary>
        public static string Excel_product_col_29 {
            get {
                return ResourceManager.GetString("Excel_product_col_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên vật tư , hàng hóa.
        /// </summary>
        public static string Excel_product_col_3 {
            get {
                return ResourceManager.GetString("Excel_product_col_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã kho.
        /// </summary>
        public static string Excel_product_col_30 {
            get {
                return ResourceManager.GetString("Excel_product_col_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đơn vị tính.
        /// </summary>
        public static string Excel_product_col_31 {
            get {
                return ResourceManager.GetString("Excel_product_col_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảm thuế.
        /// </summary>
        public static string Excel_product_col_4 {
            get {
                return ResourceManager.GetString("Excel_product_col_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhóm vật tư , hàng hóa.
        /// </summary>
        public static string Excel_product_col_5 {
            get {
                return ResourceManager.GetString("Excel_product_col_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời hạn bảo hành.
        /// </summary>
        public static string Excel_product_col_6 {
            get {
                return ResourceManager.GetString("Excel_product_col_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng tối thiểu.
        /// </summary>
        public static string Excel_product_col_7 {
            get {
                return ResourceManager.GetString("Excel_product_col_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguốc gốc.
        /// </summary>
        public static string Excel_product_col_8 {
            get {
                return ResourceManager.GetString("Excel_product_col_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string Excel_product_col_9 {
            get {
                return ResourceManager.GetString("Excel_product_col_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính.
        /// </summary>
        public static string Excel_unit_col_2 {
            get {
                return ResourceManager.GetString("Excel_unit_col_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string Excel_unit_col_3 {
            get {
                return ResourceManager.GetString("Excel_unit_col_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã kho.
        /// </summary>
        public static string Excel_warehouse_col_2 {
            get {
                return ResourceManager.GetString("Excel_warehouse_col_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên kho.
        /// </summary>
        public static string Excel_warehouse_col_3 {
            get {
                return ResourceManager.GetString("Excel_warehouse_col_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Excel_warehouse_col_4 {
            get {
                return ResourceManager.GetString("Excel_warehouse_col_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi nhánh.
        /// </summary>
        public static string Excel_warehouse_col_5 {
            get {
                return ResourceManager.GetString("Excel_warehouse_col_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi, vui lòng liên hệ MISA để được trợ giúp !.
        /// </summary>
        public static string ExceptionMISA {
            get {
                return ResourceManager.GetString("ExceptionMISA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh_sach_hang_hoa.
        /// </summary>
        public static string File_name_excel_product {
            get {
                return ResourceManager.GetString("File_name_excel_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to danh_sach_nhan_vien.
        /// </summary>
        public static string FileNameExcel {
            get {
                return ResourceManager.GetString("FileNameExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhóm vật tư , hàng hóa.
        /// </summary>
        public static string GroupCategoryList {
            get {
                return ResourceManager.GetString("GroupCategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhân viên.
        /// </summary>
        public static string NameSheet {
            get {
                return ResourceManager.GetString("NameSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách vật tư hàng hóa.
        /// </summary>
        public static string Product_list_header {
            get {
                return ResourceManager.GetString("Product_list_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách đơn vị tính.
        /// </summary>
        public static string UnitList {
            get {
                return ResourceManager.GetString("UnitList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bạn nhập lớn hơn ngày hiện tại !.
        /// </summary>
        public static string ValidateDateMess {
            get {
                return ResourceManager.GetString("ValidateDateMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường này phải là Email !.
        /// </summary>
        public static string ValidateEmailMess {
            get {
                return ResourceManager.GetString("ValidateEmailMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được phép trùng !.
        /// </summary>
        public static string ValidateEmployeeCodeMess {
            get {
                return ResourceManager.GetString("ValidateEmployeeCodeMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp hệ, vui lòng kiểm tra lại !.
        /// </summary>
        public static string ValidateErrMsg {
            get {
                return ResourceManager.GetString("ValidateErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường này không được phép để trống !.
        /// </summary>
        public static string ValidateNotEmptyMess {
            get {
                return ResourceManager.GetString("ValidateNotEmptyMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách kho.
        /// </summary>
        public static string WarehouseList {
            get {
                return ResourceManager.GetString("WarehouseList", resourceCulture);
            }
        }
    }
}
